<?php

function getQuizQuestions(): array
{
    return [
        [
            'id' => 'P1-Q1',
            'principle' => 'Perceivable',
            'guideline_code' => '1.1',
            'guideline_name' => 'Text Alternatives',
            'success_criterion' => '1.1.1 Non-text Content',
            'question' => 'Which attribute should replace the blank to provide a meaningful text alternative for this image?',
            'code_snippet' => "<img src=\"logo.png\" alt=\"\">",
            'option_a' => 'title="Logo"',
            'option_b' => 'alt="Company Logo"',
            'option_c' => 'aria-hidden="true"',
            'option_d' => 'role="presentation"',
            'correct_answer' => 'B',
            'explanation' => 'The alt attribute provides a text alternative that screen readers announce when users encounter the image. A descriptive alt value is required for informative images.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P1-Q2',
            'principle' => 'Perceivable',
            'guideline_code' => '1.2',
            'guideline_name' => 'Time-based Media',
            'success_criterion' => '1.2.2 Captions (Prerecorded)',
            'question' => 'A product video includes spoken dialogue but no captions. Which requirement best addresses this issue?',
            'code_snippet' => '<video controls src="demo.mp4"></video>',
            'option_a' => 'Add captions for prerecorded video content',
            'option_b' => 'Hide the video behind a CSS overlay',
            'option_c' => 'Use a larger font size for captions',
            'option_d' => 'Remove the audio track',
            'correct_answer' => 'A',
            'explanation' => 'WCAG requires captions for prerecorded video so people who cannot hear the audio can still understand the content.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P1-Q3',
            'principle' => 'Perceivable',
            'guideline_code' => '1.3',
            'guideline_name' => 'Adaptable',
            'success_criterion' => '1.3.1 Info and Relationships',
            'question' => 'A form uses visual labels placed next to inputs but does not associate them semantically. What is the best improvement?',
            'code_snippet' => "<label>Email</label>\n<input type=\"email\" name=\"email\">",
            'option_a' => 'Wrap the input inside a label element and associate it correctly',
            'option_b' => 'Add a border to the input only',
            'option_c' => 'Use a visually hidden div for all labels',
            'option_d' => 'Set the input to display: none',
            'correct_answer' => 'A',
            'explanation' => 'Programmatically associated labels help assistive technology users understand the purpose of form controls and improve accessibility.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P1-Q4',
            'principle' => 'Perceivable',
            'guideline_code' => '1.3',
            'guideline_name' => 'Adaptable',
            'success_criterion' => '1.3.1 Info and Relationships',
            'question' => 'A page uses only visual styling to create a heading hierarchy, but the markup is a series of div elements. What is the main problem?',
            'code_snippet' => "<div class=\"title\">Introduction</div>\n<div class=\"section\">Overview</div>",
            'option_a' => 'Screen reader users may not be able to navigate the page structure effectively',
            'option_b' => 'The page can no longer be resized',
            'option_c' => 'The page will fail keyboard access',
            'option_d' => 'The page cannot use JavaScript',
            'correct_answer' => 'A',
            'explanation' => 'Semantic heading elements communicate structure to assistive technology. Visual styling alone does not create an equivalent programmatic hierarchy.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P1-Q5',
            'principle' => 'Perceivable',
            'guideline_code' => '1.4',
            'guideline_name' => 'Distinguishable',
            'success_criterion' => '1.4.3 Contrast (Minimum)',
            'question' => 'A button uses very light gray text on a white background. Which issue is most likely?',
            'code_snippet' => "<button style=\"color:#e5e7eb; background:#fff;\">Submit</button>",
            'option_a' => 'Low color contrast that may reduce readability',
            'option_b' => 'The button needs an alt attribute',
            'option_c' => 'The button cannot be focused',
            'option_d' => 'The button must be converted to an image',
            'correct_answer' => 'A',
            'explanation' => 'Sufficient contrast between text and background helps users with low vision read content. Poor contrast can make content difficult to distinguish.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P1-Q6',
            'principle' => 'Perceivable',
            'guideline_code' => '1.1',
            'guideline_name' => 'Text Alternatives',
            'success_criterion' => '1.1.1 Non-text Content',
            'question' => 'Which code example best represents an informative image with a text alternative?',
            'code_snippet' => "<img src=\"dashboard.png\" alt=\"Sales dashboard showing revenue growth for Q3\">",
            'option_a' => 'The alt text describes the image purpose and relevant information',
            'option_b' => 'The alt text is empty to keep the layout clean',
            'option_c' => 'The alt text matches the filename only',
            'option_d' => 'The alt text is hidden with aria-hidden',
            'correct_answer' => 'A',
            'explanation' => 'Informative images need meaningful alternative text that communicates the same content or function. Empty alt text is appropriate only for decorative images.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P1-Q7',
            'principle' => 'Perceivable',
            'guideline_code' => '1.4',
            'guideline_name' => 'Distinguishable',
            'success_criterion' => '1.4.10 Reflow',
            'question' => 'A mobile page uses fixed-width columns that force horizontal scrolling at 320px width. What is the main issue?',
            'code_snippet' => "<div style=\"width: 1200px;\">...</div>",
            'option_a' => 'Content may not reflow properly for smaller screens',
            'option_b' => 'The page loses semantic structure',
            'option_c' => 'The page is automatically hidden from keyboard users',
            'option_d' => 'The page cannot include forms',
            'correct_answer' => 'A',
            'explanation' => 'Reflow allows content to be presented without requiring horizontal scrolling at small viewport sizes. Fixed-width layouts can block this experience.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P1-Q8',
            'principle' => 'Perceivable',
            'guideline_code' => '1.2',
            'guideline_name' => 'Time-based Media',
            'success_criterion' => '1.2.3 Audio Description or Media Alternative (Prerecorded)',
            'question' => 'A prerecorded training video shows important visual actions without spoken narration. Which accessibility feature is most important?',
            'code_snippet' => '<video controls src="training.mp4"></video>',
            'option_a' => 'Audio description or a text alternative describing the visual information',
            'option_b' => 'A larger background image',
            'option_c' => 'A hidden skip link',
            'option_d' => 'A longer autoplay delay',
            'correct_answer' => 'A',
            'explanation' => 'Audio description helps users who cannot see the video understand critical visual information that is not otherwise conveyed in the audio track.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P1-Q9',
            'principle' => 'Perceivable',
            'guideline_code' => '1.4',
            'guideline_name' => 'Distinguishable',
            'success_criterion' => '1.4.1 Use of Color',
            'question' => 'A status message is shown only by red text and not by any text label. Why is this a problem?',
            'code_snippet' => "<p style=\"color:red;\">Error</p>",
            'option_a' => 'Color alone may not communicate the meaning to all users',
            'option_b' => 'The status message cannot be animated',
            'option_c' => 'The text size is too large',
            'option_d' => 'The paragraph is hidden from assistive technology',
            'correct_answer' => 'A',
            'explanation' => 'Information should not rely on color alone. Users who cannot distinguish certain colors need additional indicators or labels.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P1-Q10',
            'principle' => 'Perceivable',
            'guideline_code' => '1.3',
            'guideline_name' => 'Adaptable',
            'success_criterion' => '1.3.2 Meaningful Sequence',
            'question' => 'A webpage visually orders sections as Contact, Shipping, Payment, but the DOM order is Payment, Shipping, Contact. What is the primary concern?',
            'code_snippet' => "<div style=\"order:3\">Payment</div>\n<div style=\"order:2\">Shipping</div>\n<div style=\"order:1\">Contact</div>",
            'option_a' => 'The reading order may not match the intended logical order for assistive technology users',
            'option_b' => 'The page becomes inaccessible to mouse users',
            'option_c' => 'The page can no longer use CSS',
            'option_d' => 'The content must be hidden from screen readers',
            'correct_answer' => 'A',
            'explanation' => 'A meaningful sequence ensures content is presented in a logical order. Visual reordering without corresponding content order can confuse screen reader users.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P2-Q1',
            'principle' => 'Operable',
            'guideline_code' => '2.1',
            'guideline_name' => 'Keyboard Accessible',
            'success_criterion' => '2.1.1 Keyboard',
            'question' => 'A navigation menu opens only when a mouse is clicked and cannot be operated by keyboard. Which requirement does this fail?',
            'code_snippet' => "<div onclick=\"toggleMenu()\">Menu</div>",
            'option_a' => 'Keyboard accessibility for interactive functions',
            'option_b' => 'Time-based media captions',
            'option_c' => 'Contrast minimum',
            'option_d' => 'Language of the page',
            'correct_answer' => 'A',
            'explanation' => 'All functionality available by mouse should also be usable by keyboard, unless there is a documented exception.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P2-Q2',
            'principle' => 'Operable',
            'guideline_code' => '2.2',
            'guideline_name' => 'Enough Time',
            'success_criterion' => '2.2.1 Timing Adjustable',
            'question' => 'A website automatically logs users out after 10 seconds with no warning or option to extend the session. Which guideline is most relevant?',
            'code_snippet' => 'setTimeout(logout, 10000);',
            'option_a' => 'Enough Time',
            'option_b' => 'Keyboard Accessible',
            'option_c' => 'Input Assistance',
            'option_d' => 'Compatible',
            'correct_answer' => 'A',
            'explanation' => 'Users need enough time to complete tasks and should be able to adjust or extend time limits when necessary.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P2-Q3',
            'principle' => 'Operable',
            'guideline_code' => '2.3',
            'guideline_name' => 'Seizures and Physical Reactions',
            'success_criterion' => '2.3.1 Three Flashes or Below Threshold',
            'question' => 'A promotional banner flashes rapidly in red and blue. What is the main accessibility concern?',
            'code_snippet' => "<div class=\"flash\">Limited time offer</div>",
            'option_a' => 'It could trigger seizures or distracting physical reactions',
            'option_b' => 'It reduces page readability',
            'option_c' => 'It breaks semantic heading structure',
            'option_d' => 'It must include captions',
            'correct_answer' => 'A',
            'explanation' => 'Flashing content can cause seizures for some users. Restricting flashing frequency and intensity is important to reduce risk.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P2-Q4',
            'principle' => 'Operable',
            'guideline_code' => '2.4',
            'guideline_name' => 'Navigable',
            'success_criterion' => '2.4.1 Bypass Blocks',
            'question' => 'A page includes a repeated header and several navigation links before the main content. What is the best way to improve navigation?',
            'code_snippet' => "<header>...navigation...</header>\n<main>Article content</main>",
            'option_a' => 'Add a skip link to the main content',
            'option_b' => 'Convert the header to an image',
            'option_c' => 'Remove all links from the page',
            'option_d' => 'Add more JavaScript animation',
            'correct_answer' => 'A',
            'explanation' => 'Skip links allow keyboard users to bypass repeated blocks and move directly to the main content, improving efficiency and accessibility.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P2-Q5',
            'principle' => 'Operable',
            'guideline_code' => '2.4',
            'guideline_name' => 'Navigable',
            'success_criterion' => '2.4.2 Page Titled',
            'question' => 'A website uses the same title on every page. What problem does this create?',
            'code_snippet' => '<title>Home</title>',
            'option_a' => 'Users may not know which page they are on',
            'option_b' => 'Images are missing alt text',
            'option_c' => 'The website cannot be responsive',
            'option_d' => 'The page automatically fails color contrast',
            'correct_answer' => 'A',
            'explanation' => 'Descriptive page titles help users understand the context of each page and navigate more easily, especially with multiple tabs or screen readers.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P2-Q6',
            'principle' => 'Operable',
            'guideline_code' => '2.4',
            'guideline_name' => 'Navigable',
            'success_criterion' => '2.4.4 Link Purpose (In Context)',
            'question' => 'A navigation list contains links such as “Read More”, “Learn More”, and “Details”. What is the main issue?',
            'code_snippet' => "<a href=\"/pricing\">Read More</a>\n<a href=\"/features\">Learn More</a>",
            'option_a' => 'The link purpose is ambiguous without context',
            'option_b' => 'The links need captions',
            'option_c' => 'The links are not visible in mobile view',
            'option_d' => 'The links require ARIA roles',
            'correct_answer' => 'A',
            'explanation' => 'Link text should communicate the destination or purpose clearly enough that users understand where it leads without relying on nearby hidden context.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P2-Q7',
            'principle' => 'Operable',
            'guideline_code' => '2.1',
            'guideline_name' => 'Keyboard Accessible',
            'success_criterion' => '2.1.1 Keyboard',
            'question' => 'Which feature is most important for keyboard users when tabbing through a form?',
            'code_snippet' => "<button>Submit</button>\n<input type=\"email\">",
            'option_a' => 'A visible focus indicator on each interactive element',
            'option_b' => 'A hidden image behind the form',
            'option_c' => 'A large amount of animation',
            'option_d' => 'Removing all form labels',
            'correct_answer' => 'A',
            'explanation' => 'Visible focus helps keyboard users see where they are on the page and confirm which interactive element is active.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P2-Q8',
            'principle' => 'Operable',
            'guideline_code' => '2.5',
            'guideline_name' => 'Input Modalities',
            'success_criterion' => '2.5.1 Pointer Gestures',
            'question' => 'A map requires users to complete a complex touchscreen gesture to zoom in, but no alternative method is provided. What is the concern?',
            'code_snippet' => "<button aria-label=\"Zoom in\">+</button>",
            'option_a' => 'Some users may not be able to perform the required pointer gesture',
            'option_b' => 'The page may not have enough contrast',
            'option_c' => 'The page might not have valid HTML',
            'option_d' => 'The content cannot be translated',
            'correct_answer' => 'A',
            'explanation' => 'Accessibility requires alternatives to complex pointer gestures, not just a gesture-only interaction for touch devices.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P2-Q9',
            'principle' => 'Operable',
            'guideline_code' => '2.5',
            'guideline_name' => 'Input Modalities',
            'success_criterion' => '2.5.8 Target Size (Minimum)',
            'question' => 'A web app places tiny 8px touch targets very close together. Which issue is most relevant?',
            'code_snippet' => "<button style=\"font-size:8px; padding:4px;\">OK</button>",
            'option_a' => 'Target size may be too small for touch users',
            'option_b' => 'The button may not have a visible label',
            'option_c' => 'The page requires captions',
            'option_d' => 'The button cannot show color',
            'correct_answer' => 'A',
            'explanation' => 'Touch targets should be large enough for users with limited dexterity or smaller touch devices to activate comfortably.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P2-Q10',
            'principle' => 'Operable',
            'guideline_code' => '2.2',
            'guideline_name' => 'Enough Time',
            'success_criterion' => '2.2.2 Pause, Stop, Hide',
            'question' => 'A banner auto-scrolls moving text every few seconds and cannot be paused. Which requirement is most relevant?',
            'code_snippet' => "<marquee>Breaking news...</marquee>",
            'option_a' => 'Users should be able to pause or stop moving content',
            'option_b' => 'All moving content must have transcripts',
            'option_c' => 'All colors must be high contrast',
            'option_d' => 'The page should use only buttons',
            'correct_answer' => 'A',
            'explanation' => 'Users should have control over moving, blinking, or scrolling content to avoid distraction and reduce cognitive load.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P3-Q1',
            'principle' => 'Understandable',
            'guideline_code' => '3.1',
            'guideline_name' => 'Readable',
            'success_criterion' => '3.1.1 Language of Page',
            'question' => 'A page is written in Spanish but the HTML element does not declare the language. What is the best fix?',
            'code_snippet' => "<html>\n  <body>Bienvenidos a nuestro sitio</body>\n</html>",
            'option_a' => 'Add lang="es" to the html element',
            'option_b' => 'Add a hidden image',
            'option_c' => 'Use a larger font size',
            'option_d' => 'Convert the text to uppercase',
            'correct_answer' => 'A',
            'explanation' => 'Declaring the language of the page helps screen readers pronounce text correctly and lets assistive technology interpret the content properly.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P3-Q2',
            'principle' => 'Understandable',
            'guideline_code' => '3.2',
            'guideline_name' => 'Predictable',
            'success_criterion' => '3.2.2 On Input',
            'question' => 'A form unexpectedly opens a new window when a field receives focus. Which issue is most likely?',
            'code_snippet' => "<input onfocus=\"window.open('help.html','_blank')\">",
            'option_a' => 'The interface is not predictable and may surprise users',
            'option_b' => 'The page is missing a heading',
            'option_c' => 'The input requires a transcript',
            'option_d' => 'The form cannot be animated',
            'correct_answer' => 'A',
            'explanation' => 'Users expect controls to behave in predictable ways. Unexpected changes on focus or input can be confusing and disorienting.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P3-Q3',
            'principle' => 'Understandable',
            'guideline_code' => '3.3',
            'guideline_name' => 'Input Assistance',
            'success_criterion' => '3.3.2 Labels or Instructions',
            'question' => 'A user is asked to type a username, but no instruction explains the required format. What is the most relevant improvement?',
            'code_snippet' => "<input type=\"text\" name=\"username\">",
            'option_a' => 'Add a label and clear instructions for the expected format',
            'option_b' => 'Remove the input and use an image',
            'option_c' => 'Use only a placeholder without a label',
            'option_d' => 'Convert the input to a hidden field',
            'correct_answer' => 'A',
            'explanation' => 'Users need labels and clear instructions so they understand what input is required and what format is expected.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P3-Q4',
            'principle' => 'Understandable',
            'guideline_code' => '3.1',
            'guideline_name' => 'Readable',
            'success_criterion' => '3.1.2 Language of Parts',
            'question' => 'A page contains a quotation in French within English content, but the language is not identified. What is the best solution?',
            'code_snippet' => "<p>Le rapport est disponible en ligne.</p>",
            'option_a' => 'Use a lang attribute on the phrase or element to identify the language',
            'option_b' => 'Remove the quotation and replace it with an image',
            'option_c' => 'Add a CSS animation to the text',
            'option_d' => 'Set the quote to aria-hidden=true',
            'correct_answer' => 'A',
            'explanation' => 'Language of parts ensures screen readers can correctly pronounce content in a different language than the surrounding page.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P3-Q5',
            'principle' => 'Understandable',
            'guideline_code' => '3.2',
            'guideline_name' => 'Predictable',
            'success_criterion' => '3.2.3 Consistent Navigation',
            'question' => 'A site changes the location of the main navigation menu on each page. Why is that a problem?',
            'code_snippet' => '<nav>Primary navigation</nav>',
            'option_a' => 'Users must relearn navigation on each page, increasing cognitive load',
            'option_b' => 'The page will no longer animate',
            'option_c' => 'Only touch users are affected',
            'option_d' => 'The page fails keyboard support',
            'correct_answer' => 'A',
            'explanation' => 'Consistent navigation reduces confusion and helps users build accurate mental models of the site structure.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P3-Q6',
            'principle' => 'Understandable',
            'guideline_code' => '3.3',
            'guideline_name' => 'Input Assistance',
            'success_criterion' => '3.3.1 Error Identification',
            'question' => 'A form submission fails because a required date is invalid, but the page only shows a generic error message. What should be improved?',
            'code_snippet' => "<div class=\"error\">Something is wrong</div>",
            'option_a' => 'Identify the specific field and explain the error clearly',
            'option_b' => 'Hide the error text from screen readers',
            'option_c' => 'Add more decorative images',
            'option_d' => 'Change the field to a password input',
            'correct_answer' => 'A',
            'explanation' => 'Error identification should communicate exactly what went wrong and where, so users can correct the issue without confusion.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P3-Q7',
            'principle' => 'Understandable',
            'guideline_code' => '3.3',
            'guideline_name' => 'Input Assistance',
            'success_criterion' => '3.3.3 Error Suggestion',
            'question' => 'A user enters an invalid email address. What is the best accessibility improvement?',
            'code_snippet' => "<input type=\"email\" value=\"name@\">",
            'option_a' => 'Display an error suggestion such as “Please include an @ symbol”',
            'option_b' => 'Disable the field so it cannot be edited',
            'option_c' => 'Change the font to a decorative style',
            'option_d' => 'Use a tooltip with no text',
            'correct_answer' => 'A',
            'explanation' => 'Error suggestions help users understand the problem and recover from it with minimal effort.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P3-Q8',
            'principle' => 'Understandable',
            'guideline_code' => '3.2',
            'guideline_name' => 'Predictable',
            'success_criterion' => '3.2.4 Consistent Identification',
            'question' => 'A website uses the same icon for a help button in one place and a delete button in another. What issue is most likely?',
            'code_snippet' => "<button><span>?</span></button>\n<button><span>?</span></button>",
            'option_a' => 'The function may not be consistently identified, causing confusion',
            'option_b' => 'The page will fail contrast checks',
            'option_c' => 'The buttons must be replaced with images',
            'option_d' => 'The icon needs captions for audio',
            'correct_answer' => 'A',
            'explanation' => 'Users should be able to recognize familiar controls and labels consistently across the interface, which reduces ambiguity and confusion.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P3-Q9',
            'principle' => 'Understandable',
            'guideline_code' => '3.3',
            'guideline_name' => 'Input Assistance',
            'success_criterion' => '3.3.4 Error Prevention (Legal, Financial, Data)',
            'question' => 'A checkout form lets users submit an order without a final confirmation step. Which principle is most relevant?',
            'code_snippet' => "<button>Place Order</button>",
            'option_a' => 'Input assistance through error prevention',
            'option_b' => 'Keyboard navigation',
            'option_c' => 'Color contrast',
            'option_d' => 'Media captions',
            'correct_answer' => 'A',
            'explanation' => 'Error prevention protects users from costly or irreversible mistakes by confirming critical actions before they complete them.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P3-Q10',
            'principle' => 'Understandable',
            'guideline_code' => '3.1',
            'guideline_name' => 'Readable',
            'success_criterion' => '3.1.3 Unusual Words',
            'question' => 'A technical help page uses unfamiliar acronyms without definitions. What is the main accessibility concern?',
            'code_snippet' => "<p>Use the KMS workflow to complete the KPI review.</p>",
            'option_a' => 'The content may be difficult for some users to read and understand',
            'option_b' => 'The page may be missing mouse hover states',
            'option_c' => 'The page must use ARIA landmarks',
            'option_d' => 'The text needs an alt attribute',
            'correct_answer' => 'A',
            'explanation' => 'Readable content should be understandable to the intended audience. Technical jargon or unexplained acronyms can make information harder to interpret.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P4-Q1',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.2 Name, Role, Value',
            'question' => 'A custom toggle is built with a div and JavaScript, but it does not expose a role or state. What is the issue?',
            'code_snippet' => "<div class=\"toggle\" onclick=\"toggleState()\">Off</div>",
            'option_a' => 'Assistive technology may not know the control type or state',
            'option_b' => 'The page loses keyboard focus',
            'option_c' => 'The item cannot be styled with CSS',
            'option_d' => 'The item cannot contain text',
            'correct_answer' => 'A',
            'explanation' => 'Custom components should expose roles, states, and properties so assistive technologies can interpret them correctly.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P4-Q2',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.2 Name, Role, Value',
            'question' => 'Which choice best supports compatibility with assistive technology?',
            'code_snippet' => "<button aria-expanded=\"false\" aria-controls=\"menu\">Menu</button>",
            'option_a' => 'Using proper semantic HTML and ARIA state attributes when needed',
            'option_b' => 'Using only a plain text span with no button behavior',
            'option_c' => 'Removing all labels from forms',
            'option_d' => 'Setting all content to display:none',
            'correct_answer' => 'A',
            'explanation' => 'Semantic elements and correctly exposed states help browsers and assistive technologies communicate interface elements accurately.',
            'difficulty' => 'Easy'
        ],
        [
            'id' => 'P4-Q3',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.3 Status Messages',
            'question' => 'A page updates a form status using a visual message that is not announced to screen readers. Why is this a concern?',
            'code_snippet' => "<div id=\"status\">Profile saved</div>",
            'option_a' => 'Screen reader users may not be notified that the status changed',
            'option_b' => 'The page will no longer load on mobile',
            'option_c' => 'The message cannot have color',
            'option_d' => 'The form must be hidden',
            'correct_answer' => 'A',
            'explanation' => 'Status messages should be announced or exposed to assistive technology when content updates dynamically without a page refresh.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P4-Q4',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.2 Name, Role, Value',
            'question' => 'When a custom accordion control expands, which ARIA attribute is often used to indicate its expanded state?',
            'code_snippet' => "<button aria-expanded=\"true\">More details</button>",
            'option_a' => 'aria-expanded',
            'option_b' => 'aria-flowto',
            'option_c' => 'aria-placeholder',
            'option_d' => 'aria-speak',
            'correct_answer' => 'A',
            'explanation' => 'aria-expanded communicates whether a collapsible control is currently expanded or collapsed to assistive technologies.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P4-Q5',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.1 Parsing',
            'question' => 'A developer nests a button inside a link element. What is the likely problem?',
            'code_snippet' => "<a href=\"/home\"><button>Home</button></a>",
            'option_a' => 'The markup is invalid and may confuse browsers and assistive tech',
            'option_b' => 'The page loses color contrast',
            'option_c' => 'The button becomes non-focusable',
            'option_d' => 'The content is no longer visible',
            'correct_answer' => 'A',
            'explanation' => 'Valid HTML structure matters because nested interactive elements can create ambiguous semantics and unpredictable behavior across user agents.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P4-Q6',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.2 Name, Role, Value',
            'question' => 'A checkbox uses a span styled to look like a checkbox but is not a real checkbox input. What is the likely accessibility problem?',
            'code_snippet' => "<span class=\"checkbox\">Remember me</span>",
            'option_a' => 'It may not expose a usable form control to assistive technology',
            'option_b' => 'It will not be visible',
            'option_c' => 'It must not include text',
            'option_d' => 'It cannot be styled with CSS',
            'correct_answer' => 'A',
            'explanation' => 'Native form controls provide built-in semantics and behaviors. Styling only a span does not create an equivalent accessible control.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P4-Q7',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.2 Name, Role, Value',
            'question' => 'Which solution best supports a custom drop-down menu for screen readers?',
            'code_snippet' => "<div class=\"menu\">Options</div>",
            'option_a' => 'Use a native select or add appropriate ARIA roles and states',
            'option_b' => 'Remove the menu text so the control is hidden',
            'option_c' => 'Use only CSS transforms to build the control',
            'option_d' => 'Set the menu to tabindex="-1" and no label',
            'correct_answer' => 'A',
            'explanation' => 'Accessible custom components should either use native controls or expose the correct role, state, and accessible name to assistive technologies.',
            'difficulty' => 'Moderate'
        ],
        [
            'id' => 'P4-Q8',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.3 Status Messages',
            'question' => 'A page updates cart totals using JavaScript but announces nothing to screen readers. What is the main issue?',
            'code_snippet' => "<div id=\"cart-total\">$0.00</div>",
            'option_a' => 'Users may not know that the value changed',
            'option_b' => 'The page cannot use JavaScript',
            'option_c' => 'The total must be a heading',
            'option_d' => 'The total cannot include currency',
            'correct_answer' => 'A',
            'explanation' => 'Dynamic content changes should be communicated in an accessible way, typically by updating a live region or equivalent status mechanism.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P4-Q9',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.2 Name, Role, Value',
            'question' => 'A custom radio group has no accessible name. What is the most direct issue?',
            'code_snippet' => "<div role=\"radiogroup\">\n  <div role=\"radio\">Option 1</div>\n</div>",
            'option_a' => 'Screen readers may not know what the group is for or which option is selected',
            'option_b' => 'The page cannot show text',
            'option_c' => 'The element cannot be styled',
            'option_d' => 'The page must use captions',
            'correct_answer' => 'A',
            'explanation' => 'The accessible name and state of custom controls must be exposed so assistive technologies can convey the control clearly and accurately.',
            'difficulty' => 'Challenging'
        ],
        [
            'id' => 'P4-Q10',
            'principle' => 'Robust',
            'guideline_code' => '4.1',
            'guideline_name' => 'Compatible',
            'success_criterion' => '4.1.1 Parsing',
            'question' => 'Why is valid, well-structured HTML important for compatibility with assistive technologies?',
            'code_snippet' => "<main><section><h2>Summary</h2></section></main>",
            'option_a' => 'It helps browsers and assistive technologies correctly interpret the structure and semantics',
            'option_b' => 'It guarantees all content is readable in every font',
            'option_c' => 'It ensures all pages are keyboard-only',
            'option_d' => 'It automatically adds captions to media',
            'correct_answer' => 'A',
            'explanation' => 'Well-formed, semantic HTML provides predictable structure for browsers and assistive technologies, reducing compatibility issues and misinterpretation.',
            'difficulty' => 'Challenging'
        ]
    ];
}
